import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
class Tweet {
	public static int pk = 1;
	public int id;
	public int user_id;
	public String text;
	public static Tweet create(int user_id, String tweet_text) {
		Tweet tw = new Tweet();
		tw.user_id = user_id;
		tw.text = tweet_text;
		tw.id = pk++;
		return tw;
	}
	
	public String toString() {
		return this.id+"";
	}
}
public class MiniTwitter {
	HashMap<Integer, HashSet<Integer>> follow = new HashMap<Integer, HashSet<Integer>>();
    HashMap<Integer, ArrayList<Tweet>> userTweet = new HashMap<Integer, ArrayList<Tweet>>();
    public MiniTwitter() {
        // initialize your data structure here.
    }

    // @param user_id an integer
    // @param tweet a string
    // return a tweet
    public Tweet postTweet(int user_id, String tweet_text) {
        //  Write your code here
        Tweet tw = Tweet.create(user_id, tweet_text);
        ArrayList<Tweet> tws = userTweet.get(user_id);
        if( tws == null ) {
            tws = new ArrayList<Tweet>();
            userTweet.put(user_id, tws);
        }
        tws.add(tw);
        return tw;
    }

    // @param user_id an integer
    // return a list of 10 new feeds recently
    // and sort by timeline
    public List<Tweet> getNewsFeed(int user_id) {
        // Write your code here
        ArrayList<Tweet> tws = new ArrayList<Tweet>();
        if(userTweet.get(user_id) != null) 
            tws.addAll(userTweet.get(user_id));
        if(follow.get(user_id) != null) {
            for(int fl : follow.get(user_id)) {
                if(userTweet.get(fl) != null) {
//                    System.out.println(tws);
                    tws.addAll(new ArrayList<Tweet>(userTweet.get(fl)));
                }
            }
        }
        Collections.sort(tws, new Comparator<Tweet>(){
            public int compare(Tweet t1, Tweet t2) {
        		return t1.id- t2.id;
        	}
        });
        int r = tws.size()-1;
        int l = r - 9;
        l = Math.max(0, l);
        ArrayList<Tweet> res = new ArrayList<>();
        while(r >= l) {
            res.add(tws.get(r--));
        }
        return res;
    }
        
    // @param user_id an integer
    // return a list of 10 new posts recently
    // and sort by timeline
    public List<Tweet>  getTimeline(int user_id) {
        // Write your code here
        ArrayList<Tweet> tws = userTweet.get(user_id);
        if(tws == null) return new ArrayList<Tweet>();
        Collections.sort(tws, new Comparator<Tweet>(){
            public int compare(Tweet t1, Tweet t2) {
        		return t1.id- t2.id;
        	}
        });
        int r = tws.size()-1;
        int l = r - 9;
        l = Math.max(0, l);
        ArrayList<Tweet> res = new ArrayList<>();
        while(r >= l) {
            res.add(tws.get(r--));
        }
        return res;
    }

    // @param from_user_id an integer
    // @param to_user_id an integer
    // from user_id follows to_user_id
    public void follow(int from_user_id, int to_user_id) {
        // Write your code here
        HashSet<Integer> set = follow.get(from_user_id);
        if(set == null) set = new HashSet<Integer>();
        set.add(to_user_id);
        follow.put(from_user_id, set);
    }

    // @param from_user_id an integer
    // @param to_user_id an integer
    // from user_id unfollows to_user_id
    public void unfollow(int from_user_id, int to_user_id) {
        // Write your code here
        HashSet<Integer> set = follow.get(from_user_id);
        set.remove(to_user_id);
    }
    
    public void test() {postTweet(13, "cbdefghik")         ;
    postTweet(14, "intco")             ;
    postTweet(7, "eilovelin")          ;
    postTweet(14, "elintcode")         ;
    follow(13, 5)                      ;
    follow(6, 15)                      ;
    getNewsFeed(6)                     ;
    follow(9, 5)                       ;
    postTweet(14, "velintc")           ;
    postTweet(3, "esti love ")         ;
    getNewsFeed(1)                     ;
    follow(16, 13)                     ;
    getNewsFeed(2)                     ;
    getNewsFeed(16)                    ;
    postTweet(10, "e isbest")          ;
    follow(15, 8)                      ;
    postTweet(2, "cbdefgh")            ;
    postTweet(9, "delintco")           ;
    getNewsFeed(12)                    ;
    postTweet(6, "elint")              ;
    postTweet(9, "fghik")              ;
    postTweet(16, "ntcodel")           ;
    getNewsFeed(13)                    ;
    postTweet(9, "ghikis")             ;
    follow(4, 10)                      ;
    getTimeline(8)                     ;
    postTweet(15, "defghikl")          ;
    getTimeline(4)                     ;
    getNewsFeed(12)                    ;
    postTweet(11, "cbdefghikl")        ;
    getNewsFeed(8)                     ;
    getTimeline(3)                     ;
    follow(6, 7)                       ;
    follow(15, 5)                      ;
    postTweet(1, "lintcode")           ;
    getTimeline(7)                     ;
    getTimeline(4)                     ;
    getTimeline(6)                     ;
    getTimeline(6)                     ;
    follow(10, 6)                      ;
    follow(6, 14)                      ;
    getNewsFeed(3)                     ;
    getTimeline(2)                     ;
    getNewsFeed(11)                    ;
    postTweet(4, "tcodelint")          ;
    getNewsFeed(5)                     ;
    follow(13, 2)                      ;
    getTimeline(11)                    ;
    postTweet(13, "ikisacb")           ;
    follow(4, 9)                       ;
    getTimeline(7)                     ;
    follow(8, 12)                      ;
    follow(1, 10)                      ;
    getNewsFeed(6)                     ;
    unfollow(8, 12)                    ;
    postTweet(12, "intcodea")          ;
    getTimeline(5)                     ;
    getNewsFeed(14)                    ;
    getTimeline(12)                    ;
    getTimeline(16)                    ;
    postTweet(8, "ghikl")              ;
    unfollow(15, 8)                    ;
    getNewsFeed(1)                     ;
    getNewsFeed(13)                    ;
    getNewsFeed(5)                     ;
    follow(16, 15)                     ;
    follow(13, 12)                     ;
    follow(4, 6)                       ;
    postTweet(2, "bdefg")              ;
    follow(9, 13)                      ;
    getTimeline(4)                     ;
    getNewsFeed(8)                     ;
    getNewsFeed(12)                    ;
    getTimeline(6)                     ;
    getNewsFeed(11)                    ;
    getTimeline(8)                     ;
    follow(3, 15)                      ;
    postTweet(8, "isbes")              ;
    getNewsFeed(16)                    ;
    postTweet(10, "ode isbe")          ;
    follow(16, 7)                      ;
    getNewsFeed(4)                     ;
    getNewsFeed(2)                     ;
    follow(1, 14)                      ;
    getNewsFeed(14)                    ;
    postTweet(11, "code is")           ;
    getTimeline(14)                    ;
    getTimeline(16)                    ;
    postTweet(8, "intcodeacb")         ;
    postTweet(3, "velin")              ;
    follow(14, 12)                     ;
    postTweet(3, "hikbes")             ;
    postTweet(4, "cbdef")              ;
    getTimeline(15)                    ;
    getNewsFeed(5)                     ;
    getNewsFeed(2)                     ;
    getNewsFeed(6)                     ;
    getNewsFeed(10)                    ;
    postTweet(16, "lintcode")          ;
    follow(15, 8)                      ;
    follow(10, 2)                      ;
    getTimeline(1)                     ;
    postTweet(16, "code l")            ;
    follow(9, 12)                      ;
    getNewsFeed(14)                    ;
    postTweet(7, "besti l")            ;
    follow(7, 8)                       ;
    follow(10, 8)                      ;
    getNewsFeed(9)                     ;
    postTweet(6, "deacbdefgh")         ;
    follow(5, 9)                       ;
    unfollow(10, 6)                    ;
    postTweet(11, "hiklmnl")           ;
    getNewsFeed(5)                     ;
    postTweet(3, "ti lovelin")         ;
    getNewsFeed(8)                     ;
    getNewsFeed(3)                     ;
    getTimeline(3)                     ;
    follow(3, 1)                       ;
    getNewsFeed(7)                     ;
    postTweet(7, "eacbdefghi")         ;
    getNewsFeed(11)                    ;
    postTweet(8, "codeilov")           ;
    postTweet(12, "mnlin")             ;
    postTweet(13, "lintcodea")         ;
    postTweet(9, "bdefgh")             ;
    follow(12, 13)                     ;
    getTimeline(6)                     ;
    postTweet(11, "lintco")            ;
    postTweet(13, "codei")             ;
    getTimeline(8)                     ;
    getNewsFeed(2)                     ;
    follow(2, 11)                      ;
    getNewsFeed(6)                     ;
    follow(5, 15)                      ;
    postTweet(13, "tcode ")            ;
    unfollow(6, 7)                     ;
    postTweet(8, "ilovelint")          ;
    getTimeline(7)                     ;
    postTweet(4, "lintcodel")          ;
    getNewsFeed(5)                     ;
    getTimeline(12)                    ;
    follow(16, 12)                     ;
    follow(12, 14)                     ;
    getTimeline(6)                     ;
    getTimeline(6)                     ;
    postTweet(7, "tcode lin")          ;
    postTweet(14, "lintcodel")         ;
    follow(5, 4)                       ;
    getNewsFeed(15)                    ;
    postTweet(15, "odelintco")         ;
    postTweet(7, "ntcod")              ;
    getNewsFeed(16)                    ;
    getNewsFeed(2)                     ;
    follow(6, 7)                       ;
    unfollow(12, 14)                   ;
    follow(3, 16)                      ;
    postTweet(12, "intcode i")         ;
    postTweet(4, "ikisacbde")          ;
    postTweet(9, "acbdefg")            ;
    follow(4, 13)                      ;
    getNewsFeed(2)                     ;
    postTweet(1, "hiklmn")             ;
    getTimeline(2)                     ;
    postTweet(4, "ghikli")             ;
    getNewsFeed(16)                    ;
    getTimeline(7)                     ;
    getNewsFeed(9)                     ;
    postTweet(4, "cbdefghi")           ;
    postTweet(3, "defghi")             ;
    getNewsFeed(15)                    ;
    postTweet(3, "defgh")              ;
    follow(1, 9)                       ;
    getTimeline(8)                     ;
    getNewsFeed(5)                     ;
    getNewsFeed(4)                     ;
    postTweet(13, "fghik")             ;
    getTimeline(15)                    ;
    postTweet(13, "code i")            ;
    getNewsFeed(2)                     ;
    postTweet(6, "tcode")              ;
    follow(15, 16)                     ;
    getTimeline(15)                    ;
    postTweet(7, "ntcode")             ;
    getNewsFeed(8)                     ;
    postTweet(6, "tcode")              ;
    getNewsFeed(14)                    ;
    getNewsFeed(4)                     ;
    postTweet(10, " love")             ;
    postTweet(11, "ikbest")            ;
    follow(11, 9)                      ;
    getNewsFeed(8)                     ;
    follow(8, 10)                      ;
    postTweet(5, "codel")              ;
    unfollow(3, 15)                    ;
    postTweet(15, "tcodeac")           ;
    postTweet(9, "cbdefghik")          ;
    postTweet(1, "iloveli")            ;
    unfollow(5, 4)                     ;
    follow(2, 10)                      ;
    getNewsFeed(5)                     ;
    postTweet(5, "ikisacbde")          ;
    follow(14, 2)                      ;
    getTimeline(5)                     ;
    postTweet(8, "ntcode li")          ;
    getNewsFeed(12)                    ;
    postTweet(14, "ntcode")            ;
    getNewsFeed(3)                     ;
    getTimeline(6)                     ;
    getNewsFeed(16)                    ;
    postTweet(7, "lintco")             ;
    postTweet(2, "efghi")              ;
    postTweet(11, " love lin")         ;
    follow(3, 12)                      ;
    unfollow(9, 13)                    ;
    getNewsFeed(13)                    ;
    getNewsFeed(12)                    ;
    postTweet(9, "ntcod")              ;
    follow(7, 15)                      ;
    follow(16, 1)                      ;
    postTweet(2, "ntcodeac")           ;
    postTweet(9, "elintcodea")         ;
    follow(14, 9)                      ;
    postTweet(16, "ntcodeac")          ;
    postTweet(6, "iklmnlint")          ;
    getNewsFeed(9)                     ;
    postTweet(4, "e lintco")           ;
    unfollow(12, 13)                   ;
    follow(5, 13)                      ;
    getNewsFeed(4)                     ;
    postTweet(4, "ode isbest")         ;
    postTweet(8, "besti lov")          ;
    getNewsFeed(1)                     ;
    follow(6, 11)                      ;
    getNewsFeed(8)                     ;
    postTweet(4, "lintcodel")          ;
    postTweet(10, "lintcod")           ;
    getNewsFeed(3)                     ;
    postTweet(12, "intco")             ;
    getNewsFeed(12)                    ;
    follow(16, 9)                      ;
    follow(2, 5)                       ;
    getNewsFeed(8)                     ;
    follow(6, 9)                       ;
    follow(15, 4)                      ;
    follow(11, 8)                      ;
    postTweet(8, "kbest")              ;
    getNewsFeed(5)                     ;
    getTimeline(12)                    ;
    unfollow(13, 2)                    ;
    getNewsFeed(15)                    ;
    getNewsFeed(5)                     ;
    follow(11, 4)                      ;
    getNewsFeed(7)                     ;
    getTimeline(5)                     ;
    getNewsFeed(8)                     ;
    postTweet(12, "cbdefghiki")        ;
    follow(13, 8)                      ;
    postTweet(16, "codeacbd")          ;
    getNewsFeed(4)                     ;
    getNewsFeed(11)                    ;
    getTimeline(11)                    ;
    follow(12, 15)                     ;
    follow(6, 4)                       ;
    getTimeline(5)                     ;
    postTweet(13, "intcodei")          ;
    follow(8, 1)                       ;
    follow(13, 6)                      ;
    follow(1, 6)                       ;
    getTimeline(3)                     ;
    getNewsFeed(1)                     ;
    postTweet(12, "i love")            ;
    getTimeline(6)                     ;
    postTweet(2, " lintcode")          ;
    getNewsFeed(11)                    ;
    postTweet(12, "lintcod")           ;
    unfollow(1, 14)                    ;
    unfollow(3, 16)                    ;
    postTweet(8, " love lin")          ;
    getNewsFeed(3)                     ;
    getTimeline(10)                    ;
    postTweet(13, "sacbdefgh")         ;
    follow(7, 12)                      ;
    getNewsFeed(16)                    ;
    getNewsFeed(8)                     ;
    getTimeline(8)                     ;
    getTimeline(7)                     ;
    unfollow(11, 9)                    ;
    getNewsFeed(11)                    ;
    follow(7, 2)                       ;
    getNewsFeed(7)                     ;
    getNewsFeed(15)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(12)                    ;
    getTimeline(16)                    ;
    postTweet(4, "intcodea")           ;
    getNewsFeed(10)                    ;
    postTweet(15, "klintco")           ;
    postTweet(4, "fghiki")             ;
    postTweet(10, "kbesti lov")        ;
    postTweet(13, "velin")             ;
    postTweet(6, "i lov")              ;
    postTweet(1, "lintcodeac")         ;
    getNewsFeed(14)                    ;
    getNewsFeed(11)                    ;
    getTimeline(14)                    ;
    postTweet(7, "cbdefghi")           ;
    getNewsFeed(14)                    ;
    getNewsFeed(4)                     ;
    getNewsFeed(16)                    ;
    getTimeline(4)                     ;
    getNewsFeed(11)                    ;
    getNewsFeed(16)                    ;
    postTweet(12, "ghiklmnli")         ;
    follow(4, 5)                       ;
    getNewsFeed(15)                    ;
    unfollow(6, 11)                    ;
    getTimeline(9)                     ;
    postTweet(3, "de is")              ;
    getNewsFeed(3)                     ;
    follow(7, 14)                      ;
    getNewsFeed(15)                    ;
    getNewsFeed(9)                     ;
    postTweet(4, "sbesti ")            ;
    getTimeline(12)                    ;
    getNewsFeed(3)                     ;
    postTweet(11, " loveli")           ;
    postTweet(7, "efghikisac")         ;
    postTweet(16, "iklmnl")            ;
    postTweet(15, "hikisac")           ;
    postTweet(1, "odelintc")           ;
    getTimeline(10)                    ;
    postTweet(2, "codeacbdef")         ;
    follow(7, 16)                      ;
    follow(14, 10)                     ;
    unfollow(9, 12)                    ;
    postTweet(16, "acbdefgh")          ;
    postTweet(14, "ntcode")            ;
    getNewsFeed(5)                     ;
    postTweet(1, "codeli")             ;
    postTweet(7, "odeacb")             ;
    getNewsFeed(3)                     ;
    follow(14, 1)                      ;
    follow(5, 16)                      ;
    postTweet(11, "code isb")          ;
    postTweet(8, "defghi")             ;
    getNewsFeed(12)                    ;
    postTweet(15, "ghikbesti ")        ;
    follow(5, 3)                       ;
    follow(3, 8)                       ;
    getTimeline(15)                    ;
    follow(7, 6)                       ;
    follow(6, 1)                       ;
    getNewsFeed(12)                    ;
    getTimeline(4)                     ;
    getNewsFeed(3)                     ;
    getNewsFeed(9)                     ;
    postTweet(14, "e lintc")           ;
    postTweet(7, "eilov")              ;
    postTweet(1, "tcodel")             ;
    follow(12, 11)                     ;
    getTimeline(11)                    ;
    follow(3, 7)                       ;
    follow(8, 4)                       ;
    postTweet(8, "fghikb")             ;
    postTweet(5, "defghiki")           ;
    follow(12, 5)                      ;
    getTimeline(9)                     ;
    unfollow(10, 2)                    ;
    follow(5, 1)                       ;
    postTweet(14, "acbde")             ;
    getTimeline(6)                     ;
    follow(12, 10)                     ;
    postTweet(15, "ntcod")             ;
    follow(11, 6)                      ;
    postTweet(5, "sbest")              ;
    getNewsFeed(6)                     ;
    follow(10, 4)                      ;
    unfollow(10, 4)                    ;
    postTweet(10, "ikbesti lo")        ;
    getTimeline(2)                     ;
    follow(1, 16)                      ;
    getNewsFeed(1)                     ;
    getNewsFeed(2)                     ;
    postTweet(15, "isbesti")           ;
    postTweet(5, "ntcodeac")           ;
    getNewsFeed(16)                    ;
    postTweet(16, "intcodel")          ;
    postTweet(8, "besti")              ;
    postTweet(1, "lintc")              ;
    getNewsFeed(13)                    ;
    getNewsFeed(13)                    ;
    follow(4, 8)                       ;
    unfollow(8, 1)                     ;
    getTimeline(15)                    ;
    unfollow(11, 8)                    ;
    getNewsFeed(2)                     ;
    getTimeline(12)                    ;
    follow(10, 7)                      ;
    postTweet(16, "fghiklin")          ;
    postTweet(7, "mnlint")             ;
    postTweet(9, "efghik")             ;
    getNewsFeed(4)                     ;
    postTweet(10, "intco")             ;
    follow(8, 13)                      ;
    getNewsFeed(9)                     ;
    getTimeline(3)                     ;
    postTweet(5, "intcodeli")          ;
    getTimeline(9)                     ;
    postTweet(10, "intcodeac")         ;
    getTimeline(13)                    ;
    postTweet(11, "intcode i")         ;
    getTimeline(9)                     ;
    postTweet(11, "lintcode")          ;
    postTweet(6, "code isb")           ;
    getTimeline(9)                     ;
    postTweet(2, "ghikisac")           ;
    getTimeline(6)                     ;
    follow(4, 2)                       ;
    getTimeline(14)                    ;
    postTweet(4, "odelint")            ;
    getNewsFeed(7)                     ;
    getNewsFeed(1)                     ;
    getTimeline(4)                     ;
    postTweet(9, "ilove")              ;
    postTweet(5, "code lintc")         ;
    getTimeline(1)                     ;
    follow(12, 3)                      ;
    follow(2, 13)                      ;
    getNewsFeed(7)                     ;
    postTweet(2, "ode lintco")         ;
    postTweet(4, "sti love ")          ;
    postTweet(3, "iklintco")           ;
    getNewsFeed(9)                     ;
    unfollow(7, 15)                    ;
    postTweet(8, "defgh")              ;
    getNewsFeed(14)                    ;
    follow(6, 13)                      ;
    getNewsFeed(5)                     ;
    getNewsFeed(8)                     ;
    follow(10, 11)                     ;
    getNewsFeed(3)                     ;
    getNewsFeed(15)                    ;
    follow(15, 3)                      ;
    postTweet(6, "defghi")             ;
    follow(10, 4)                      ;
    getTimeline(12)                    ;
    postTweet(14, "sbesti l")          ;
    getTimeline(2)                     ;
    postTweet(10, "intcodeac")         ;
    postTweet(13, "ghiklmnli")         ;
    getNewsFeed(4)                     ;
    postTweet(13, " isbesti ")         ;
    getTimeline(1)                     ;
    getNewsFeed(5)                     ;
    postTweet(13, "defghi")            ;
    getNewsFeed(9)                     ;
    postTweet(5, "tcode")              ;
    postTweet(4, "ve lintcod")         ;
    postTweet(7, "ntcode l")           ;
    getNewsFeed(8)                     ;
    follow(14, 4)                      ;
    postTweet(16, "deilove")           ;
    getTimeline(5)                     ;
    postTweet(16, "cbdefghi")          ;
    getNewsFeed(12)                    ;
    postTweet(7, "ilovelintc")         ;
    postTweet(15, "love lin")          ;
    getNewsFeed(9)                     ;
    follow(12, 6)                      ;
    unfollow(8, 4)                     ;
    unfollow(6, 7)                     ;
    postTweet(11, "fghik")             ;
    getTimeline(14)                    ;
    postTweet(1, "elintcode")          ;
    postTweet(9, "ode i")              ;
    postTweet(16, "de isbes")          ;
    unfollow(16, 15)                   ;
    getTimeline(1)                     ;
    follow(2, 4)                       ;
    postTweet(6, " lovelint")          ;
    getNewsFeed(9)                     ;
    postTweet(8, "ntcode li")          ;
    unfollow(3, 1)                     ;
    postTweet(8, "ntcode ")            ;
    getNewsFeed(11)                    ;
    getNewsFeed(10)                    ;
    postTweet(1, "ghikisac")           ;
    getTimeline(13)                    ;
    getTimeline(7)                     ;
    getTimeline(15)                    ;
    getTimeline(9)                     ;
    postTweet(4, "ghikli")             ;
    postTweet(16, "ghiklmnlin")        ;
    follow(8, 7)                       ;
    getNewsFeed(16)                    ;
    getNewsFeed(1)                     ;
    follow(10, 16)                     ;
    unfollow(7, 8)                     ;
    postTweet(1, "hikbe")              ;
    getNewsFeed(14)                    ;
    follow(5, 7)                       ;
    getTimeline(14)                    ;
    getNewsFeed(3)                     ;
    postTweet(11, "lintco")            ;
    postTweet(15, "bdefghi")           ;
    unfollow(7, 12)                    ;
    follow(12, 4)                      ;
    getTimeline(5)                     ;
    getTimeline(16)                    ;
    postTweet(1, " lovel")             ;
    unfollow(16, 9)                    ;
    getNewsFeed(10)                    ;
    follow(7, 15)                      ;
    postTweet(10, "ti loveli")         ;
    getNewsFeed(5)                     ;
    getTimeline(3)                     ;
    getTimeline(8)                     ;
    getNewsFeed(1)                     ;
    postTweet(15, "elintc")            ;
    postTweet(3, "intcode")            ;
    postTweet(11, "ghiklmnl")          ;
    getTimeline(5)                     ;
    follow(1, 14)                      ;
    follow(8, 12)                      ;
    getTimeline(12)                    ;
    postTweet(3, "bdefghikbe")         ;
    getTimeline(7)                     ;
    postTweet(7, "lintcode")           ;
    follow(16, 6)                      ;
    postTweet(12, "intcodeacb")        ;
    postTweet(2, "intcodeil")          ;
    postTweet(8, "ntcodeilov")         ;
    postTweet(10, "tcode")             ;
    postTweet(15, "lintcode")          ;
    follow(4, 16)                      ;
    unfollow(10, 7)                    ;
    follow(9, 10)                      ;
    getNewsFeed(15)                    ;
    postTweet(11, "ikbes")             ;
    unfollow(13, 5)                    ;
    getNewsFeed(1)                     ;
    postTweet(7, "code is")            ;
    postTweet(10, "codelint")          ;
    postTweet(8, "tcode isbe")         ;
    follow(11, 14)                     ;
    getTimeline(5)                     ;
    getNewsFeed(11)                    ;
    postTweet(1, " lovel")             ;
    getNewsFeed(16)                    ;
    postTweet(10, "ikbesti ")          ;
    postTweet(10, "intcodeli")         ;
    follow(8, 15)                      ;
    unfollow(8, 7)                     ;
    getNewsFeed(8)                     ;
    postTweet(16, "lmnlintcod")        ;
    postTweet(2, "efghikl")            ;
    follow(5, 12)                      ;
    postTweet(7, "deilove")            ;
    getNewsFeed(5)                     ;
    getTimeline(16)                    ;
    getNewsFeed(8)                     ;
    postTweet(4, "lmnlin")             ;
    getTimeline(16)                    ;
    getTimeline(14)                    ;
    getNewsFeed(10)                    ;
    getNewsFeed(12)                    ;
    follow(2, 3)                       ;
    follow(12, 1)                      ;
    postTweet(1, "intcodeacb")         ;
    getNewsFeed(15)                    ;
    postTweet(13, "lintco")            ;
    getNewsFeed(11)                    ;
    getNewsFeed(13)                    ;
    getNewsFeed(13)                    ;
    getNewsFeed(3)                     ;
    getNewsFeed(7)                     ;
    follow(7, 9)                       ;
    follow(8, 16)                      ;
    unfollow(5, 13)                    ;
    follow(13, 7)                      ;
    postTweet(7, "isbest")             ;
    postTweet(13, "delint")            ;
    getNewsFeed(14)                    ;
    unfollow(14, 1)                    ;
    postTweet(8, "ntcodeacbd")         ;
    postTweet(14, "intcode")           ;
    getNewsFeed(8)                     ;
    postTweet(7, "ode isbe")           ;
    getNewsFeed(2)                     ;
    getNewsFeed(1)                     ;
    getNewsFeed(16)                    ;
    postTweet(10, "intcode i")         ;
    unfollow(5, 16)                    ;
    getNewsFeed(7)                     ;
    getTimeline(6)                     ;
    unfollow(10, 16)                   ;
    getNewsFeed(8)                     ;
    getNewsFeed(5)                     ;
    postTweet(10, "mnlintc")           ;
    getNewsFeed(12)                    ;
    postTweet(9, "fghik")              ;
    follow(6, 10)                      ;
    getNewsFeed(7)                     ;
    postTweet(4, "klmnlint")           ;
    postTweet(15, "kisacbd")           ;
    getNewsFeed(8)                     ;
    postTweet(2, "ghikbesti")          ;
    getTimeline(4)                     ;
    getNewsFeed(8)                     ;
    getNewsFeed(10)                    ;
    postTweet(3, "deilovelin")         ;
    follow(16, 2)                      ;
    getTimeline(9)                     ;
    postTweet(14, "oveli")             ;
    follow(6, 3)                       ;
    follow(15, 9)                      ;
    postTweet(11, "code is")           ;
    postTweet(14, "intcod")            ;
    getTimeline(7)                     ;
    follow(3, 2)                       ;
    postTweet(12, "efghiklmn")         ;
    getNewsFeed(11)                    ;
    getNewsFeed(12)                    ;
    getNewsFeed(1)                     ;
    postTweet(7, "ntcode isb")         ;
    unfollow(13, 6)                    ;
    getTimeline(9)                     ;
    follow(16, 5)                      ;
    getNewsFeed(9)                     ;
    postTweet(8, "delintco")           ;
    follow(9, 12)                      ;
    postTweet(5, "cbdefghi")           ;
    getTimeline(5)                     ;
    getTimeline(11)                    ;
    postTweet(11, "efghi")             ;
    postTweet(11, "delint")            ;
    getNewsFeed(3)                     ;
    postTweet(4, "de isbest")          ;
    getNewsFeed(5)                     ;
    postTweet(2, "fghikbest")          ;
    postTweet(12, "lintcode i")        ;
    getNewsFeed(1)                     ;
    getTimeline(16)                    ;
    postTweet(9, "delintcode")         ;
    getNewsFeed(3)                     ;
    unfollow(2, 3)                     ;
    unfollow(5, 15)                    ;
    unfollow(11, 4)                    ;
    postTweet(12, "efghiki")           ;
    unfollow(5, 12)                    ;
    follow(1, 5)                       ;
    getNewsFeed(6)                     ;
    postTweet(10, "odeacb")            ;
    getNewsFeed(12)                    ;
    follow(1, 8)                       ;
    follow(7, 1)                       ;
    getTimeline(13)                    ;
    unfollow(7, 1)                     ;
    getNewsFeed(16)                    ;
    postTweet(7, "sbesti lo")          ;
    postTweet(10, "odeilov")           ;
    postTweet(12, "acbde")             ;
    unfollow(7, 2)                     ;
    getNewsFeed(5)                     ;
    postTweet(13, "code ")             ;
    getNewsFeed(4)                     ;
    postTweet(6, "intcod")             ;
    getTimeline(7)                     ;
    getNewsFeed(5)                     ;
    getTimeline(6)                     ;
    getNewsFeed(14)                    ;
    unfollow(4, 8)                     ;
    postTweet(3, "lintcodeli")         ;
    follow(4, 8)                       ;
    getNewsFeed(8)                     ;
    getNewsFeed(13)                    ;
    getNewsFeed(5)                     ;
    unfollow(1, 6)                     ;
    getTimeline(2)                     ;
    getNewsFeed(13)                    ;
    postTweet(15, "ntcod")             ;
    postTweet(1, "acbde")              ;
    postTweet(5, "ode isbest")         ;
    getNewsFeed(6)                     ;
    unfollow(14, 12)                   ;
    follow(4, 12)                      ;
    postTweet(11, "lintco")            ;
    postTweet(2, "lintcod")            ;
    postTweet(8, "bdefghikis")         ;
    getNewsFeed(6)                     ;
    follow(15, 11)                     ;
    getNewsFeed(2)                     ;
    getNewsFeed(4)                     ;
    unfollow(8, 13)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(1)                     ;
    unfollow(10, 8)                    ;
    getNewsFeed(10)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(10)                    ;
    postTweet(8, "acbdef")             ;
    postTweet(11, "ove li")            ;
    getTimeline(15)                    ;
    getTimeline(1)                     ;
    getTimeline(10)                    ;
    postTweet(4, "tcode isb")          ;
    follow(10, 8)                      ;
    postTweet(14, "iloveli")           ;
    follow(16, 11)                     ;
    getNewsFeed(6)                     ;
    getTimeline(16)                    ;
    getNewsFeed(16)                    ;
    getNewsFeed(2)                     ;
    follow(3, 5)                       ;
    postTweet(8, "lintcodea")          ;
    follow(4, 15)                      ;
    postTweet(11, "sbesti l")          ;
    unfollow(5, 9)                     ;
    getNewsFeed(2)                     ;
    postTweet(8, "hiklmnlin")          ;
    getTimeline(15)                    ;
    follow(9, 8)                       ;
    getNewsFeed(14)                    ;
    follow(8, 5)                       ;
    getNewsFeed(16)                    ;
    getTimeline(15)                    ;
    getNewsFeed(3)                     ;
    postTweet(3, "ntcode isb")         ;
    postTweet(13, "deiloveli")         ;
    postTweet(11, "nlintco")           ;
    getNewsFeed(6)                     ;
    postTweet(1, "elintcode")          ;
    getTimeline(2)                     ;
    getNewsFeed(8)                     ;
    getTimeline(12)                    ;
    postTweet(5, "isacbde")            ;
    getNewsFeed(13)                    ;
    follow(12, 14)                     ;
    postTweet(5, "delintcode")         ;
    follow(8, 13)                      ;
    postTweet(15, "velintcod")         ;
    postTweet(3, "ghiklm")             ;
    follow(9, 1)                       ;
    unfollow(7, 9)                     ;
    postTweet(5, "hiklin")             ;
    postTweet(16, "tcodea")            ;
    getNewsFeed(5)                     ;
    getTimeline(10)                    ;
    postTweet(12, "besti l")           ;
    getNewsFeed(10)                    ;
    follow(10, 13)                     ;
    getTimeline(7)                     ;
    postTweet(2, "tcode lin")          ;
    getNewsFeed(8)                     ;
    postTweet(3, "klintc")             ;
    follow(8, 3)                       ;
    postTweet(6, "tcode l")            ;
    getNewsFeed(15)                    ;
    getNewsFeed(5)                     ;
    getTimeline(13)                    ;
    getTimeline(6)                     ;
    getNewsFeed(11)                    ;
    getTimeline(11)                    ;
    getTimeline(16)                    ;
    getNewsFeed(8)                     ;
    postTweet(7, "efghik")             ;
    postTweet(7, "de lintco")          ;
    getNewsFeed(2)                     ;
    follow(11, 8)                      ;
    follow(14, 1)                      ;
    postTweet(7, "acbdefghik")         ;
    postTweet(15, "efghi")             ;
    postTweet(1, "codelint")           ;
    getNewsFeed(13)                    ;
    follow(7, 4)                       ;
    postTweet(2, "ode isbes")          ;
    postTweet(2, "lintcodea")          ;
    postTweet(13, "lintco")            ;
    getNewsFeed(7)                     ;
    getNewsFeed(2)                     ;
    getNewsFeed(13)                    ;
    postTweet(2, "bdefg")              ;
    follow(5, 16)                      ;
    postTweet(11, "mnlintc")           ;
    unfollow(15, 11)                   ;
    postTweet(8, "iklintco")           ;
    getNewsFeed(11)                    ;
    unfollow(8, 3)                     ;
    follow(8, 4)                       ;
    follow(14, 15)                     ;
    getNewsFeed(3)                     ;
    postTweet(11, "esti l")            ;
    postTweet(2, "elintcode")          ;
    postTweet(6, "tcodel")             ;
    getTimeline(3)                     ;
    getNewsFeed(10)                    ;
    getTimeline(7)                     ;
    postTweet(4, "velintcode")         ;
    getTimeline(3)                     ;
    postTweet(2, "besti lov")          ;
    follow(9, 4)                       ;
    postTweet(2, "ghikli")             ;
    postTweet(16, "lintcod")           ;
    getNewsFeed(6)                     ;
    getNewsFeed(3)                     ;
    getNewsFeed(6)                     ;
    postTweet(11, "ntcode")            ;
    postTweet(4, "bdefghik")           ;
    getNewsFeed(3)                     ;
    getNewsFeed(13)                    ;
    getNewsFeed(11)                    ;
    getNewsFeed(10)                    ;
    getTimeline(5)                     ;
    postTweet(5, "lintcodei")          ;
    postTweet(12, "ode i")             ;
    getTimeline(12)                    ;
    postTweet(15, "tcode lin")         ;
    follow(10, 15)                     ;
    postTweet(1, "odeil")              ;
    follow(3, 14)                      ;
    getTimeline(6)                     ;
    getTimeline(13)                    ;
    postTweet(10, "kbesti l")          ;
    postTweet(15, "i love")            ;
    getNewsFeed(10)                    ;
    postTweet(1, "besti l")            ;
    unfollow(9, 4)                     ;
    getNewsFeed(16)                    ;
    getTimeline(6)                     ;
    postTweet(14, "ovelin")            ;
    unfollow(3, 2)                     ;
    getNewsFeed(14)                    ;
    getTimeline(8)                     ;
    getNewsFeed(2)                     ;
    getTimeline(13)                    ;
    getNewsFeed(9)                     ;
    getNewsFeed(16)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(1)                     ;
    postTweet(8, "tcodelin")           ;
    postTweet(8, "ode i")              ;
    getTimeline(13)                    ;
    follow(3, 9)                       ;
    postTweet(16, "cbdefghik")         ;
    getTimeline(15)                    ;
    postTweet(13, "lintc")             ;
    getTimeline(15)                    ;
    getNewsFeed(15)                    ;
    postTweet(14, "ikbesti")           ;
    getNewsFeed(9)                     ;
    unfollow(4, 9)                     ;
    postTweet(10, "ode lintco")        ;
    postTweet(10, "efghikisac")        ;
    getNewsFeed(9)                     ;
    follow(15, 2)                      ;
    unfollow(8, 12)                    ;
    getTimeline(15)                    ;
    unfollow(16, 5)                    ;
    getTimeline(12)                    ;
    getTimeline(6)                     ;
    postTweet(11, "ntcod")             ;
    getNewsFeed(5)                     ;
    getNewsFeed(13)                    ;
    follow(13, 2)                      ;
    follow(14, 16)                     ;
    unfollow(8, 4)                     ;
    postTweet(2, "tcode ")             ;
    getTimeline(11)                    ;
    getNewsFeed(16)                    ;
    postTweet(2, "ntcode ")            ;
    getTimeline(8)                     ;
    getNewsFeed(12)                    ;
    getTimeline(8)                     ;
    follow(8, 1)                       ;
    getNewsFeed(13)                    ;
    getTimeline(9)                     ;
    postTweet(3, "ntcodelin")          ;
    getNewsFeed(15)                    ;
    follow(9, 11)                      ;
    postTweet(16, "lintcodei")         ;
    getNewsFeed(6)                     ;
    getTimeline(1)                     ;
    getTimeline(13)                    ;
    getTimeline(8)                     ;
    postTweet(1, "ode is")             ;
    follow(7, 8)                       ;
    getNewsFeed(12)                    ;
    getNewsFeed(8)                     ;
    postTweet(7, "ti lo")              ;
    getTimeline(12)                    ;
    getNewsFeed(16)                    ;
    getTimeline(2)                     ;
    getTimeline(3)                     ;
    postTweet(8, "intcode")            ;
    getTimeline(2)                     ;
    postTweet(14, "efghikli")          ;
    unfollow(14, 2)                    ;
    follow(1, 4)                       ;
    follow(13, 5)                      ;
    getNewsFeed(10)                    ;
    getTimeline(5)                     ;
    getNewsFeed(8)                     ;
    getTimeline(7)                     ;
    getNewsFeed(9)                     ;
    postTweet(4, "code lint")          ;
    getNewsFeed(6)                     ;
    postTweet(9, "e isbesti ")         ;
    getNewsFeed(12)                    ;
    getNewsFeed(5)                     ;
    postTweet(2, "eacbdefghi")         ;
    postTweet(8, "ntcode ")            ;
    unfollow(8, 13)                    ;
    postTweet(15, " lintco")           ;
    postTweet(8, "intcode")            ;
    getTimeline(2)                     ;
    follow(16, 15)                     ;
    follow(5, 12)                      ;
    getNewsFeed(10)                    ;
    postTweet(1, "klmnli")             ;
    getTimeline(9)                     ;
    postTweet(3, "bdefghiki")          ;
    getNewsFeed(13)                    ;
    getNewsFeed(5)                     ;
    getTimeline(6)                     ;
    getNewsFeed(9)                     ;
    follow(1, 2)                       ;
    getTimeline(6)                     ;
    postTweet(3, "besti l")            ;
    getNewsFeed(15)                    ;
    getNewsFeed(4)                     ;
    getNewsFeed(13)                    ;
    getNewsFeed(9)                     ;
    getTimeline(8)                     ;
    postTweet(16, "odeli")             ;
    postTweet(14, "kbesti lov")        ;
    postTweet(15, "love l")            ;
    postTweet(2, "deacbdefg")          ;
    postTweet(5, "hiklint")            ;
    follow(14, 8)                      ;
    postTweet(14, "tcode i")           ;
    unfollow(16, 1)                    ;
    getNewsFeed(11)                    ;
    getNewsFeed(10)                    ;
    postTweet(3, " love lin")          ;
    postTweet(16, "bdefghik")          ;
    getTimeline(13)                    ;
    getNewsFeed(14)                    ;
    postTweet(3, "deacb")              ;
    getNewsFeed(4)                     ;
    postTweet(14, "esti ")             ;
    getTimeline(15)                    ;
    getNewsFeed(10)                    ;
    postTweet(10, "isacbdefgh")        ;
    getNewsFeed(2)                     ;
    postTweet(14, "e lintcod")         ;
    postTweet(9, "lintc")              ;
    postTweet(4, "hikbesti l")         ;
    postTweet(4, "defgh")              ;
    getTimeline(11)                    ;
    follow(7, 11)                      ;
    getTimeline(4)                     ;
    getNewsFeed(8)                     ;
    unfollow(16, 15)                   ;
    getNewsFeed(7)                     ;
    postTweet(9, "codeacbd")           ;
    postTweet(4, "deiloveli")          ;
    getTimeline(14)                    ;
    getNewsFeed(3)                     ;
    follow(10, 16)                     ;
    postTweet(13, "odeli")             ;
    getNewsFeed(15)                    ;
    follow(16, 5)                      ;
    getNewsFeed(10)                    ;
    postTweet(16, "ode li")            ;
    getNewsFeed(3)                     ;
    follow(14, 5)                      ;
    getNewsFeed(10)                    ;
    unfollow(7, 8)                     ;
    unfollow(4, 12)                    ;
    postTweet(9, "ntcode i")           ;
    getNewsFeed(6)                     ;
    unfollow(15, 2)                    ;
    postTweet(11, " isbesti l")        ;
    getTimeline(4)                     ;
    getTimeline(4)                     ;
    unfollow(11, 8)                    ;
    getNewsFeed(13)                    ;
    getTimeline(9)                     ;
    follow(15, 7)                      ;
    getNewsFeed(4)                     ;
    getNewsFeed(11)                    ;
    unfollow(6, 4)                     ;
    getTimeline(10)                    ;
    postTweet(2, "ntcodeli")           ;
    follow(1, 3)                       ;
    postTweet(16, "cbdefghikl")        ;
    follow(15, 1)                      ;
    postTweet(15, "delintcode")        ;
    postTweet(5, "odelint")            ;
    getNewsFeed(11)                    ;
    unfollow(11, 6)                    ;
    postTweet(16, "delintcod")         ;
    unfollow(9, 1)                     ;
    getTimeline(15)                    ;
    postTweet(14, "lovelintco")        ;
    getTimeline(7)                     ;
    getNewsFeed(15)                    ;
    postTweet(9, "velintc")            ;
    postTweet(6, "lintcodel")          ;
    postTweet(13, "velin")             ;
    follow(13, 11)                     ;
    postTweet(1, "elintco")            ;
    getNewsFeed(9)                     ;
    unfollow(5, 7)                     ;
    getNewsFeed(4)                     ;
    getNewsFeed(4)                     ;
    follow(3, 13)                      ;
    postTweet(9, "efghikisac")         ;
    getNewsFeed(7)                     ;
    getNewsFeed(13)                    ;
    unfollow(16, 5)                    ;
    unfollow(16, 12)                   ;
    postTweet(8, "besti")              ;
    getTimeline(12)                    ;
    getNewsFeed(15)                    ;
    getTimeline(11)                    ;
    postTweet(11, "bdefgh")            ;
    getNewsFeed(9)                     ;
    postTweet(1, "de isbesti")         ;
    getTimeline(10)                    ;
    postTweet(7, "tcodel")             ;
    getTimeline(9)                     ;
    follow(9, 7)                       ;
    follow(4, 11)                      ;
    postTweet(16, "hiklmnlint")        ;
    postTweet(16, "codeacbde")         ;
    getNewsFeed(13)                    ;
    getNewsFeed(13)                    ;
    postTweet(4, "lintcode")           ;
    postTweet(10, "sacbdefgh")         ;
    postTweet(9, "delintco")           ;
    getTimeline(7)                     ;
    getTimeline(10)                    ;
    getTimeline(15)                    ;
    getNewsFeed(12)                    ;
    postTweet(13, "intcode i")         ;
    follow(6, 5)                       ;
    postTweet(7, "tcodeli")            ;
    getNewsFeed(7)                     ;
    unfollow(15, 5)                    ;
    getNewsFeed(15)                    ;
    unfollow(15, 3)                    ;
    postTweet(16, "ntcod")             ;
    postTweet(15, "ntcodeacbd")        ;
    getNewsFeed(8)                     ;
    unfollow(8, 1)                     ;
    postTweet(16, "hikisacb")          ;
    getNewsFeed(2)                     ;
    getTimeline(4)                     ;
    getNewsFeed(3)                     ;
    postTweet(1, "nlintcodel")         ;
    postTweet(2, "odeilove")           ;
    getNewsFeed(3)                     ;
    postTweet(3, "e lintcod")          ;
    getTimeline(12)                    ;
    postTweet(3, "e lintcode")         ;
    getNewsFeed(6)                     ;
    postTweet(1, "intco")              ;
    postTweet(1, "deacb")              ;
    postTweet(12, "fghikli")           ;
    getNewsFeed(5)                     ;
    follow(11, 9)                      ;
    getNewsFeed(2)                     ;
    postTweet(11, "intco")             ;
    postTweet(4, "ve lint")            ;
    getTimeline(5)                     ;
    getTimeline(13)                    ;
    getTimeline(8)                     ;
    getNewsFeed(2)                     ;
    getTimeline(7)                     ;
    getTimeline(15)                    ;
    getNewsFeed(16)                    ;
    getTimeline(15)                    ;
    postTweet(14, "iklintco")          ;
    getTimeline(6)                     ;
    getNewsFeed(12)                    ;
    getNewsFeed(6)                     ;
    postTweet(10, "tcodea")            ;
    getNewsFeed(16)                    ;
    getNewsFeed(3)                     ;
    follow(14, 2)                      ;
    getNewsFeed(15)                    ;
    unfollow(4, 6)                     ;
    getTimeline(16)                    ;
    unfollow(12, 14)                   ;
    postTweet(13, "odelintco")         ;
    postTweet(11, "ode lint")          ;
    postTweet(12, "ovelin")            ;
    getNewsFeed(15)                    ;
    getNewsFeed(14)                    ;
    postTweet(14, "defghikl")          ;
    postTweet(1, "fghikbest")          ;
    getTimeline(8)                     ;
    follow(2, 1)                       ;
    unfollow(1, 9)                     ;
    getTimeline(5)                     ;
    postTweet(5, "besti love")         ;
    follow(2, 12)                      ;
    follow(8, 6)                       ;
    follow(16, 9)                      ;
    getNewsFeed(4)                     ;
    getNewsFeed(13)                    ;
    unfollow(3, 5)                     ;
    unfollow(3, 13)                    ;
    postTweet(9, "ntcode l")           ;
    getNewsFeed(11)                    ;
    getNewsFeed(1)                     ;
    unfollow(4, 10)                    ;
    postTweet(14, "e lintcod")         ;
    postTweet(10, "odelint")           ;
    getNewsFeed(8)                     ;
    getTimeline(10)                    ;
    getTimeline(12)                    ;
    postTweet(1, "deacbdef")           ;
    getNewsFeed(14)                    ;
    getNewsFeed(6)                     ;
    postTweet(5, "tcode is")           ;
    getTimeline(16)                    ;
    getNewsFeed(8)                     ;
    getTimeline(7)                     ;
    getNewsFeed(13)                    ;
    follow(6, 7)                       ;
    postTweet(1, "hiklm")              ;
    unfollow(1, 8)                     ;
    follow(12, 13)                     ;
    postTweet(12, "sti lo")            ;
    getNewsFeed(2)                     ;
    getNewsFeed(15)                    ;
    postTweet(11, "acbdefgh")          ;
    postTweet(4, "bdefghik")           ;
    unfollow(12, 1)                    ;
    follow(12, 8)                      ;
    getTimeline(16)                    ;
    unfollow(7, 16)                    ;
    getTimeline(14)                    ;
    getTimeline(2)                     ;
    follow(2, 15)                      ;
    postTweet(3, "odelintc")           ;
    postTweet(6, "hiklm")              ;
    postTweet(5, "fghikli")            ;
    follow(10, 3)                      ;
    follow(9, 16)                      ;
    getNewsFeed(2)                     ;
    getNewsFeed(5)                     ;
    getNewsFeed(15)                    ;
    postTweet(12, "elintcode")         ;
    getTimeline(12)                    ;
    getTimeline(14)                    ;
    getNewsFeed(16)                    ;
    unfollow(1, 2)                     ;
    postTweet(16, "efghik")            ;
    follow(15, 14)                     ;
    follow(14, 13)                     ;
    unfollow(11, 9)                    ;
    postTweet(15, "besti love")        ;
    postTweet(8, "nlintcode")          ;
    postTweet(9, "lintc")              ;
    postTweet(1, "bdefghikl")          ;
    unfollow(3, 8)                     ;
    getTimeline(8)                     ;
    getNewsFeed(11)                    ;
    unfollow(10, 4)                    ;
    postTweet(9, "ode lin")            ;
    postTweet(15, "intcodeilo")        ;
    postTweet(9, "elintc")             ;
    follow(15, 2)                      ;
    getNewsFeed(9)                     ;
    getNewsFeed(13)                    ;
    getNewsFeed(13)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(12)                    ;
    getNewsFeed(4)                     ;
    getNewsFeed(5)                     ;
    postTweet(5, " love lin")          ;
    getNewsFeed(12)                    ;
    follow(7, 12)                      ;
    postTweet(4, "hikbest")            ;
    unfollow(1, 10)                    ;
    getNewsFeed(8)                     ;
    getNewsFeed(6)                     ;
    follow(10, 5)                      ;
    postTweet(7, "sti lov")            ;
    postTweet(7, "ve lintc")           ;
    getNewsFeed(9)                     ;
    getNewsFeed(7)                     ;
    getTimeline(9)                     ;
    postTweet(8, "i love")             ;
    getNewsFeed(16)                    ;
    postTweet(16, "elint")             ;
    postTweet(15, "intcode l")         ;
    getTimeline(5)                     ;
    postTweet(6, "elintcode")          ;
    postTweet(15, "efghiklmnl")        ;
    postTweet(16, "tcodeacb")          ;
    getTimeline(15)                    ;
    getTimeline(5)                     ;
    getTimeline(16)                    ;
    postTweet(6, "odelin")             ;
    getTimeline(9)                     ;
    getNewsFeed(12)                    ;
    getNewsFeed(1)                     ;
    getNewsFeed(4)                     ;
    getNewsFeed(2)                     ;
    getTimeline(2)                     ;
    getTimeline(16)                    ;
    follow(7, 2)                       ;
    postTweet(8, "ode isbe")           ;
    unfollow(4, 11)                    ;
    postTweet(9, "elintcode")          ;
    postTweet(7, "elintcode")          ;
    getNewsFeed(16)                    ;
    follow(10, 12)                     ;
    postTweet(12, "ikbes")             ;
    getNewsFeed(9)                     ;
    getNewsFeed(1)                     ;
    unfollow(2, 1)                     ;
    getNewsFeed(15)                    ;
    follow(11, 1)                      ;
    getNewsFeed(6)                     ;
    getTimeline(7)                     ;
    postTweet(13, "i love lin")        ;
    postTweet(5, "odeilove")           ;
    postTweet(3, "eacbde")             ;
    getTimeline(9)                     ;
    getNewsFeed(11)                    ;
    postTweet(6, "ikisacbde")          ;
    unfollow(4, 16)                    ;
    getNewsFeed(10)                    ;
    postTweet(13, " lintcode")         ;
    getTimeline(3)                     ;
    postTweet(5, "velint")             ;
    postTweet(15, "odelintcod")        ;
    postTweet(4, "de isb")             ;
    postTweet(2, "ghiklin")            ;
    postTweet(15, "bdefghi")           ;
    getTimeline(11)                    ;
    postTweet(8, "bdefg")              ;
    getNewsFeed(12)                    ;
    getTimeline(15)                    ;
    getNewsFeed(12)                    ;
    getTimeline(9)                     ;
    postTweet(10, "de is")             ;
    postTweet(2, "bdefghiklm")         ;
    postTweet(12, " lintco")           ;
    follow(5, 14)                      ;
    getNewsFeed(9)                     ;
    follow(14, 6)                      ;
    postTweet(5, "elintc")             ;
    getNewsFeed(9)                     ;
    postTweet(9, "deacbdefgh")         ;
    postTweet(5, "ghikis")             ;
    getTimeline(11)                    ;
    getNewsFeed(10)                    ;
    getNewsFeed(9)                     ;
    unfollow(15, 8)                    ;
    getNewsFeed(10)                    ;
    postTweet(2, "bdefghikl")          ;
    postTweet(16, "ilovelintc")        ;
    postTweet(10, "efghiklmnl")        ;
    postTweet(7, "lintcod")            ;
    getNewsFeed(2)                     ;
    postTweet(8, "iklmnli")            ;
    postTweet(3, "acbdefgh")           ;
    getNewsFeed(11)                    ;
    postTweet(1, "intcode is")         ;
    getNewsFeed(6)                     ;
    getTimeline(13)                    ;
    getNewsFeed(14)                    ;
    getNewsFeed(13)                    ;
    postTweet(15, "tcodelin")          ;
    getNewsFeed(1)                     ;
    getNewsFeed(12)                    ;
    postTweet(9, "delin")              ;
    getNewsFeed(1)                     ;
    unfollow(13, 5)                    ;
    follow(1, 2)                       ;
    follow(8, 2)                       ;
    getNewsFeed(1)                     ;
    postTweet(10, "klint")             ;
    postTweet(10, "efghikb")           ;
    getNewsFeed(9)                     ;
    postTweet(5, "code i")             ;
    follow(2, 1)                       ;
    postTweet(11, " isbesti ")         ;
    unfollow(1, 5)                     ;
    getNewsFeed(14)                    ;
    getNewsFeed(6)                     ;
    unfollow(4, 13)                    ;
    getTimeline(1)                     ;
    getNewsFeed(1)                     ;
    unfollow(16, 2)                    ;
    postTweet(11, "isbesti ")          ;
    getTimeline(1)                     ;
    postTweet(4, "besti")              ;
    follow(3, 2)                       ;
    postTweet(16, "fghikbest")         ;
    postTweet(15, "ntcod")             ;
    unfollow(11, 1)                    ;
    postTweet(3, "fghikis")            ;
    getNewsFeed(7)                     ;
    follow(14, 3)                      ;
    postTweet(13, "velin")             ;
    postTweet(11, "odelint")           ;
    follow(8, 13)                      ;
    postTweet(6, "e isbesti ")         ;
    getTimeline(6)                     ;
    getNewsFeed(7)                     ;
    follow(13, 15)                     ;
    getNewsFeed(11)                    ;
    follow(4, 9)                       ;
    getNewsFeed(14)                    ;
    getNewsFeed(11)                    ;
    getNewsFeed(16)                    ;
    getTimeline(4)                     ;
    postTweet(3, "odelin")             ;
    getNewsFeed(15)                    ;
    follow(13, 10)                     ;
    postTweet(6, "hikbesti l")         ;
    postTweet(6, "tcodelint")          ;
    getNewsFeed(12)                    ;
    follow(10, 6)                      ;
    follow(4, 11)                      ;
    postTweet(9, "lintcodel")          ;
    follow(16, 14)                     ;
    unfollow(14, 16)                   ;
    postTweet(14, "e lintc")           ;
    getNewsFeed(12)                    ;
    getNewsFeed(7)                     ;
    getTimeline(14)                    ;
    getNewsFeed(4)                     ;
    follow(9, 6)                       ;
    getNewsFeed(14)                    ;
    unfollow(14, 2)                    ;
    postTweet(15, "ti love l")         ;
    postTweet(12, "ntcodeilo")         ;
    getNewsFeed(7)                     ;}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		MiniTwitter mt = new MiniTwitter();
		mt.test();
	}

}
