package Math;
/**
 * leetcode 389. Find the Difference
 * @author zg55
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindtheDifference {
    public char findTheDifference(String s, String t) {
        int r = 0;
        for(char c:s.toCharArray()) r^=c;
        for(char c:t.toCharArray()) r^=c;
        return (char)r;
    }
}
